/**
* FrmInicial.java
* May 9, 2023 12:21:01 AM
* 
*/ 

package GUI;

import Dominio.Cuidador;
import Dominio.Habitat;
import Dominio.Itinerario;
import itson.Control.CtrlRegistrarEspecie;
import itson.Control.FabricaLogica;
import itson.Control.ILogica;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;


/**
 * Descripción de la clase: 
 * 
 * @author 
 */
public class FrmInicial extends javax.swing.JFrame {

    ILogica ctrlHabitat;
    ILogica ctrlEspecie;
    ILogica ctrlItinerario;
    ILogica ctrlQueja;

     /**
     * Crea un nuevo formulario FrmInicial.
     *
     */
    public FrmInicial() {
        this.setVisible(true);
        ctrlHabitat=FabricaLogica.crearInstancia();
        ctrlEspecie=FabricaLogica.crearInstancia();
        ctrlItinerario=FabricaLogica.crearInstancia();
        ctrlQueja = FabricaLogica.crearInstancia();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        pnlSeparador3 = new javax.swing.JPanel();
        pnlSeparador2 = new javax.swing.JPanel();
        pnlSeparador1 = new javax.swing.JPanel();
        pnlInicial = new javax.swing.JPanel();
        lblZoologico = new javax.swing.JLabel();
        btnRegActItinerario = new javax.swing.JButton();
        btnRegistrarHabitat = new javax.swing.JButton();
        btnAtencionVisitantes = new javax.swing.JButton();
        lblItinerarios = new javax.swing.JLabel();
        lblHabitats = new javax.swing.JLabel();
        lblQueja = new javax.swing.JLabel();
        lblEspecies = new javax.swing.JLabel();
        btnRegActEspecie1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pantalla principal");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFondo.setBackground(new java.awt.Color(238, 189, 102));
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSeparador3.setBackground(new java.awt.Color(106, 69, 4));
        pnlSeparador3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlFondo.add(pnlSeparador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 690, 20));

        pnlSeparador2.setBackground(new java.awt.Color(106, 69, 4));
        pnlSeparador2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlFondo.add(pnlSeparador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 10, 220));

        pnlSeparador1.setBackground(new java.awt.Color(106, 69, 4));
        pnlSeparador1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlFondo.add(pnlSeparador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 10, 220));

        pnlInicial.setBackground(new java.awt.Color(106, 69, 4));
        pnlInicial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblZoologico.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        lblZoologico.setForeground(new java.awt.Color(255, 255, 255));
        lblZoologico.setText("Zoológico Cd. Obregón");
        pnlInicial.add(lblZoologico, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        pnlFondo.add(pnlInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 70));

        btnRegActItinerario.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 20)); // NOI18N
        btnRegActItinerario.setForeground(new java.awt.Color(106, 69, 4));
        btnRegActItinerario.setText("Registrar / Actualizar");
        btnRegActItinerario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActItinerarioActionPerformed(evt);
            }
        });
        pnlFondo.add(btnRegActItinerario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, -1));

        btnRegistrarHabitat.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 20)); // NOI18N
        btnRegistrarHabitat.setForeground(new java.awt.Color(106, 69, 4));
        btnRegistrarHabitat.setText("Registrar");
        btnRegistrarHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarHabitatActionPerformed(evt);
            }
        });
        pnlFondo.add(btnRegistrarHabitat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        btnAtencionVisitantes.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        btnAtencionVisitantes.setForeground(new java.awt.Color(106, 69, 4));
        btnAtencionVisitantes.setText("Atención visitantes");
        btnAtencionVisitantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtencionVisitantesActionPerformed(evt);
            }
        });
        pnlFondo.add(btnAtencionVisitantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        lblItinerarios.setFont(new java.awt.Font("Segoe Print", 1, 25)); // NOI18N
        lblItinerarios.setForeground(new java.awt.Color(255, 255, 255));
        lblItinerarios.setText("Itinerarios");
        pnlFondo.add(lblItinerarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        lblHabitats.setFont(new java.awt.Font("Segoe Print", 1, 25)); // NOI18N
        lblHabitats.setForeground(new java.awt.Color(255, 255, 255));
        lblHabitats.setText("Hábitats");
        pnlFondo.add(lblHabitats, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        lblQueja.setFont(new java.awt.Font("Segoe Print", 1, 20)); // NOI18N
        lblQueja.setForeground(new java.awt.Color(255, 255, 255));
        lblQueja.setText("¿Tienes alguna queja?");
        pnlFondo.add(lblQueja, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, -1));

        lblEspecies.setFont(new java.awt.Font("Segoe Print", 1, 25)); // NOI18N
        lblEspecies.setForeground(new java.awt.Color(255, 255, 255));
        lblEspecies.setText("Especies");
        pnlFondo.add(lblEspecies, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        btnRegActEspecie1.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 20)); // NOI18N
        btnRegActEspecie1.setForeground(new java.awt.Color(106, 69, 4));
        btnRegActEspecie1.setText("Registrar / Actualizar");
        btnRegActEspecie1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActEspecie1ActionPerformed(evt);
            }
        });
        pnlFondo.add(btnRegActEspecie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        getContentPane().add(pnlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarHabitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarHabitatActionPerformed
        // TODO add your handling code here:
        this.seleccionaRegistrarHabitat();
    }//GEN-LAST:event_btnRegistrarHabitatActionPerformed

    private void btnAtencionVisitantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtencionVisitantesActionPerformed
        // TODO add your handling code here:
        this.seleccionaAtencionVisitantes();
    }//GEN-LAST:event_btnAtencionVisitantesActionPerformed

    private void btnRegActItinerarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActItinerarioActionPerformed
        // TODO add your handling code here:
        this.seleccionaRegActItinerario();
    }//GEN-LAST:event_btnRegActItinerarioActionPerformed

    private void btnRegActEspecie1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActEspecie1ActionPerformed
        this.seleccionaRegistActEspecie();
    }//GEN-LAST:event_btnRegActEspecie1ActionPerformed

    /**
     * Método que indica las acciones a seguir cuando el actor selecciona registrar hábitat.
     */
   public void seleccionaRegistrarHabitat(){
       LinkedList<Object> arreglo = new LinkedList();
       arreglo=ctrlHabitat.recuperarDatosHabitats();
       FrmRegistrarHabitat frm = new FrmRegistrarHabitat(arreglo);
       frm.setVisible(true);
       this.setVisible(false);
       this.dispose();
   }

   /**
     * Método que indica las acciones a seguir cuando el actor selecciona 
     * registrar / actualizar especie.
     */
   public void seleccionaRegistActEspecie() {
       List<Habitat> habitats=ctrlEspecie.recuperarHabitats();
       List<Cuidador> cuidadores=ctrlEspecie.recuperarCuidadores();
       FrmRegistrarEspecie frm = new FrmRegistrarEspecie(habitats, cuidadores);
       frm.setVisible(true);
       this.setVisible(false);
       this.dispose();
   }
   
   /**
     * Método que indica las acciones a seguir cuando el actor selecciona 
     * registrar / actualizar itinerario.
     */
   public void seleccionaRegActItinerario(){
       LinkedList<Object> datos=ctrlItinerario.recuperaDatosItinerario();
       FrmItinerarios itinerario=new FrmItinerarios(datos);
       this.setVisible(false);
       itinerario.setVisible(true);
       this.dispose();
   }
   
   /**
     * Método que indica las acciones a seguir cuando el actor selecciona 
     * atención visitantes.
     */
   public void seleccionaAtencionVisitantes(){
       List<Itinerario> itinerarios =  ctrlQueja.recuperarItinerarios();
       FrmQuejas frm = new FrmQuejas(itinerarios);
       frm.setVisible(true);
       this.dispose();
   }
   
   /**
    * Método que muestra un mensaje de error.
    */
   public void muestraError(){
       JOptionPane.showMessageDialog(this, "Error al recuperar los datos", "Error", JOptionPane.ERROR_MESSAGE);
   }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtencionVisitantes;
    private javax.swing.JButton btnRegActEspecie1;
    private javax.swing.JButton btnRegActItinerario;
    private javax.swing.JButton btnRegistrarHabitat;
    private javax.swing.JLabel lblEspecies;
    private javax.swing.JLabel lblHabitats;
    private javax.swing.JLabel lblItinerarios;
    private javax.swing.JLabel lblQueja;
    private javax.swing.JLabel lblZoologico;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlInicial;
    private javax.swing.JPanel pnlSeparador1;
    private javax.swing.JPanel pnlSeparador2;
    private javax.swing.JPanel pnlSeparador3;
    // End of variables declaration//GEN-END:variables

}
