/**
* FrmRegistrarHabitat.java
* May 9, 2023 12:21:18 AM
* 
*/ 

package GUI;

/**
 * Descripción de la clase: 
 * 
 * @author Joel Antonio Lopez Cota ID:228926
 */
public class FrmRegistrarHabitat extends javax.swing.JFrame {

    /** Creates new form FrmRegistrarHabitat */
    public FrmRegistrarHabitat() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   public void despliegaDatos(){
       
   }
   public void seleccionaVerificar(){
   
   }

   public void despliegaHabitatExistente(){
   }
   
   public  void activaCamposRegistro(){
       
   }
   
   public void seleccionaAgregaContinente(){
       
   }
   
   public void mueveContinenteSelect(){
       
   }
   public void seleccionaGuardar(){
       
   }
   
   public void verificarCamposVacios(){
       
   }
   
   public void muestraMsjCamposVacios(){
       
   }
   
   public void muestraMsjExito(){
       
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
